---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
  environment:
    - TEST_MONGO_URI=mongodb://me:root_password@mongo4:27017
  image: "clippings:dev"
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity
    ports:
      - "8000:8000"

  app:
    <<: *common
    restart: "no"
    ports:
      - "8000:8000"

  mongo4:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=me
      - MONGO_INITDB_ROOT_PASSWORD=root_password
      - MONGO_INITDB_DATABASE=clippings_db
