---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
  image: "clippings:dev"
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity
    ports:
      - "8000:8000"

  app:
    <<: *common
    restart: "no"
    ports:
      - "8000:8000"

  mongo:
    image: mongo:8.0.1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=me
      - MONGO_INITDB_ROOT_PASSWORD=root_password
      - MONGO_INITDB_DATABASE=clippings_db
    ports:
      - "27017:27017"
