---

x-common: &common
  build:
    target: development
    context: .
    dockerfile: Dockerfile-dev
  image: "clippings:dev"
#  env_file: .env
  volumes:
    - .:/opt/code

services:
  devtools:
    <<: *common
    command: sleep infinity
    ports:
      - "8000:8000"

  app:
    <<: *common
    restart: "no"
    ports:
      - "8000:8000"

  mongo4:
    image: mongo:4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./createUser.js:/docker-entrypoint-initdb.d/createUser.js
      - ./volumes_data/mongo4:/data/db
