default:
  mongo:
    uri: mongodb://mongo:27017

testing:
  adapters:
    books_storage: mock
    users_storage: mock
    deleted_hash_storage: mock
    book_info_client: mock
  mongo:
    uri: mongodb://me:root_password@mongo:27017
