default:
  mongo:
    uri: mongodb://mongo:27017

testing:
  adapters:
    books_storage: memory
    users_storage: memory
    deleted_hash_storage: memory
    book_info_client: mock
  mongo:
    uri: mongodb://me:root_password@mongo:27017
